### PR TITLE
Tpot update

### PR DESCRIPTION
**Pull request by hupereir**
Cumulated update on TPOT online monitoring
- load calibration from root file
- added Hits-above-threshold vs sample time distribution and vertical lines to tell what distribution is good
- only add "signal" hits to charge distribution, charge profiles
- calculated "true" occupancy based on number of complete events (rather than frames)

@pinkenburg for this to work one need to have a proper calibration file in $TPOTCALIB
The file can be found at SDCC at: /phenix/u/hpereira/sphenix/install/share/onlmon/tpot/TPOT_Pedestal_000.root
Unfortunately on ebdc39 for instance, TPOTCALIB is set to /home/repo/Debian/OnlMon/share/onlmon/tpot, of which I have no write access. 
How do I write a file there ?

### CODE REVIEW

**Comment by pinkenburg** [comment]
TPOT_Pedestal_000.root needs to be checked in under tpot/calib and then installed as a data file in the Makefile.am. The make install will then copy it to the correct place

**Comment by hupereir** [comment]
> TPOT_Pedestal_000.root needs to be checked in under tpot/calib and then installed as a data file in the Makefile.am. The make install will then copy it to the correct place

mmm. ok. This is a root file though (binary), though admittedly small (61k). And we might need to update it over time. 
I am not sure how often, because noise levels have been really stable in TPOT so far, but still. 
Would there not be a possiblity to put it to some place that is not saved on git ? 
should I instead add another env variable to the tpot setup scripts, that points to somewhere writable by phnxrc on ebdc39 ?

**Comment by pinkenburg** [comment]
I would say - right now we should go with just checking this in (we had root files in PHENIX as well). If this becomes too cumbersome we can think of something else

**Comment by hupereir** [comment]
Done !

**Pull request merged**
